# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json and package-lock.json are copied
COPY package*.json ./

# Install dependencies (ignoring prepare scripts to avoid auto-build if necessary)
RUN npm install --ignore-scripts

# Build the project explicitly
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Bundle app source
# Expose a volume if necessary, but here we assume a command line tool

# Default command
CMD ["node", "dist/index.js"]
